### PR TITLE
Add turkish

### PR DESCRIPTION
**Pull request by koheiw**
Add TR dictionary

### CODE REVIEW

**Comment by koheiw** [comment]
@LungtaSEKI, thanks for you PRs. I merged both and getting ready to release in a new version of the package.

It is failing the test because the dictionary does not match "Great Britain".  Do you think you need to edit the dictionary?

```r
> txt_tr <- c("Bu İrlanda hakkında bir makale.",
+             "Bu Büyük Britanya hakkında bir makale.")
> toks_tr <- tokens(txt_tr)
> tokens_lookup(toks_tr, data_dictionary_newsmap_tr, levels = 3)
Tokens consisting of 2 documents.
text1 :
[1] "IE"

text2 :
character(0)
```

**Comment by LungtaSEKI** [comment]
> @LungtaSEKI, thanks for you PRs. I merged both and getting ready to release in a new version of the package.
> 
> It is failing the test because the dictionary does not match "Great Britain". Do you think you need to edit the dictionary?
> 
> ```r
> > txt_tr <- c("Bu İrlanda hakkında bir makale.",
> +             "Bu Büyük Britanya hakkında bir makale.")
> > toks_tr <- tokens(txt_tr)
> > tokens_lookup(toks_tr, data_dictionary_newsmap_tr, levels = 3)
> Tokens consisting of 2 documents.
> text1 :
> [1] "IE"
> 
> text2 :
> character(0)
> ```

@koheiw My aplogies for getting back to you so late. I have just added Britanya and corrected other typos. I'd really appreciate it if you could check them.

**Comment by koheiw** [comment]
@LungtaSEKI Where can I find the updated file? It you could edit file on this branch.

**Comment by koheiw** [comment]
Done. Thanks @LungtaSEKI.

**Pull request merged**
