### PR TITLE
Traditional Chinese Dictionary.

### PR DESCRIPTION
**Pull request by chainsawriot**
I don't want to create breaking changes by renaming the existing simplified Chinese dictionary to `data_dictionary_newsmap_zh_hans`. Let's just keep that as `data_dictionary_newsmap_zh`. The Traditional Chinese dictionary is named `data_dictionary_newsmap_zh_hant` (based on the ISO-639). One potential controversial issue here is the addition of the term "中華民國" <sup>1</sup> in the dictionary as one lexicon of Taiwan. The reason for adding the term is not political, rather, a practical one: the Traditional Chinese coverage of Taiwan in Hong Kong and Taiwan media sometimes label Taiwan as the Republic of China.

1: the Republic of China (the official name of Taiwan). It is not the same as "中華人民共和國", the People's Republic of China.

### CODE REVIEW

**Comment by koheiw** [comment]
"hant" and "hans" are from [ISO-15924](https://en.wikipedia.org/wiki/ISO_15924), not [ISO-639](
https://iso639-3.sil.org/code/zho). Since very few people know ISO-639 code, combination of language code and country code like [locale](https://en.wikipedia.org/wiki/Locale_(computer_software)) would be most user friendly.

Language | Code
-- | --
Chinese (Hong Kong) | zh_hk
Chinese (PRC) | zh_cn
Chinese (Singapore) | zh_sg
Chinese (Taiwan) | zh_tw

**Comment by koheiw** [comment]
I can see your point. Do you have a word for "中華民國" in simplified Chinese? Do many people use the word to refer to Taiwan?

**Comment by chainsawriot** [comment]
The simplified Chinese version of the word is `中华民国` and I haven't added this term into the Simplified Chinese dictionary. In the simplified Chinese media of the PRC, this term is also used quite often but only used to describe the regime in the China proper from 1912 to 1949. In the PRC's perspective, ROC does not exist anymore and used. But the term is also used very rarely to refer to the Taipei Government, for instance, coverage about Taiwan Independence Movements. In that context, the term is quoted.

But, this term is used very frequently in Traditional Chinese Media in Taiwan and Hong Kong to refer to the Taipei government, in particular, the coverage of the Cross-Strait relations between Taipei and Beijing or the legitimacy of the Taipei government.

If the newsmap algorithm works as promised, it should be able to pick up the term 中華民國 as a descriptor of Taiwan. So I don't mind removing the term, for the equivalence's sake between dictionaries.

**Comment by chainsawriot** [comment]
> "hant" and "hans" are from [ISO-15924](https://en.wikipedia.org/wiki/ISO_15924), not [ISO-639](https://iso639-3.sil.org/code/zho). Since very few people know ISO-639 code, combination of language code and country code like [locale](https://en.wikipedia.org/wiki/Locale_(computer_software)) would be most user friendly.
> 
> Language	Code
> Chinese (Hong Kong)	zh_hk
> Chinese (PRC)	zh_cn
> Chinese (Singapore)	zh_sg
> Chinese (Taiwan)	zh_tw

Yes, you are right. Sorry for the confusion between 15924 and 639.
For simplicity's sake, I think we can refer to the dictionaries as `zh_cn` and `zh_tw`. For the people in/from Hong Kong (e.g. me), we used to computers with the locale `zh-tw` rather than the relatively recent `zh-hk`.

**Comment by koheiw** [comment]
Good, let's name them `zh_cn` and `zh_tw`. We would never use other codes but good to have the room for extension. It makes sense that 中華民國 is used often but 中华民国 is not. Let's only include 中華民國 in `zh_tw`.

If you PR passes Travis test, I will merge.

**Comment by chainsawriot** [comment]
I have updated the names of the Chinese dictionaries accordingly. The reason for the failed Travis-CI is the two Chinese test cases I added to `test-textmodel_newsmap.R`. They run perfectly fine on my machine. But I don't know why it doesn't work on Travis.

**Comment by koheiw** [comment]
Thanks. I will have a look at the Chinese test. I might add a `skip_on_travis()`.

**Comment by koheiw** [comment]
Address #6

**Pull request merged**
