### PR TITLE
Add the Ukrainian spelling for the capital of UA

### PR DESCRIPTION
**Pull request by koheiw**
Add the capital of UA with the Ukrainian spelling (Kyiv) along with the (conventional) Russian spelling (Kiew).

@stefan-mueller and @giucarny , can you tell what are German and Italian words for Kyiv?

### CODE REVIEW

**Comment by giucarny** [comment]
> @stefan-mueller and @giucarny , can you tell what are German and Italian words for Kyiv?

Hi Kohei, the Italian word is Kiev.

**Comment by stefan-mueller** [comment]
The German words are _Kiew_ and _Kyjiw_. See also: https://de.wikipedia.org/wiki/Kiew#Schreibweise

**Comment by koheiw** [comment]
Thank you both. It is interesting that the Italian did not change the spelling.

**Comment by koheiw** [comment]
@daiyamao and @eladseg , I believe we do not need to add new words for Arabic or Hebrew for Kyiv. Can you confirm?

**Comment by eladseg** [comment]
> @daiyamao and @eladseg , I believe we do not need to add new words for Arabic or Hebrew for Kyiv. Can you confirm?

Yes, I checked it and it is fine!

**Comment by daiyamao** [comment]
I also checked and found it was not necessary to change it.

**Pull request merged**
